# This is the current stage that you're on.
#
# Whenever you want to advance to the next stage,
# bump this to the next number.
current_stage: 3

# Set this to true if you want debug logs.
#
# These can be VERY verbose, so we suggest turning them off
# unless you really need them.
debug: false
